# Site settings
title: Ping Wu's Personal Website
email: pingwu AT mail.ustc.edu.cn
description: Ping Wu's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
baseurl: ""

# url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://pingwuu.github.io/"

# twitter_username: jekyllrb
github_username: pingwuu
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/pingwuu/pingwuu.github.com/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/pingwuu/pingwuu.github.com/new/master/
#########################################

disqus_url: "http://pingwuu.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
